version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ticketing-app"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
  ticketing-app:
    build: .
networks:
  webnet:
    driver: bridge
volumes:
  initdb:



